'''
Provides access to metadata about the cultures from the Farmhouse Registry at
https://www.garshol.priv.no/download/farmhouse/kveik.html
'''

colors = {
    'kveik-north' : ('#0D5CA0', 'white'),
    'kveik-south' : ('#81B8D6', 'black'),
    'gong'        : ('#0F745E', 'white'),
    'berm'        : ('#70C4B4', 'black'),
    'latvia'      : ('#FED40A', 'black'),
    'lithuania'   : ('#F88E18', 'black'),
    'russia'      : ('#944E15', 'white'),
    'wild'        : ('#FFFFFF', 'black'),
}

culturemap = {
    '1': 'kveik-south',
    '10': 'kveik-north',
    '11': 'kveik-north',
    '12': 'kveik-north',
    '13': 'kveik-north',
    '14': 'kveik-south',
    '15': 'kveik-south',
    '16': 'lithuania',
    '17': 'kveik-north',
    '18': 'kveik-north',
    '19': 'kveik-south',
    '2': 'kveik-south',
    '20': 'kveik-north',
    '21': 'kveik-north',
    '22': 'kveik-north',
    '23': 'kveik-north',
    '24': 'kveik-south',
    '25': 'kveik-north',
    '26': 'gong',
    '27': 'gong',
    '28': 'gong',
    '29': 'kveik-north',
    '3': 'kveik-north',
    '30': 'kveik-north',
    '31': 'kveik-north',
    '32': 'lithuania',
    '33': 'lithuania',
    '34': 'lithuania',
    '35': 'kveik-north',
    '37': 'lithuania',
    '38': 'kveik-south',
    '39': 'russia',
    '40': 'russia',
    '41': 'kveik-north',
    '42': 'latvia',
    '43': 'kveik-north',
    '44': 'kveik-south',
    '45': 'latvia',
    '46': 'lithuania',
    '47': 'kveik-north',
    '48': 'kveik-north',
    '5': 'kveik-north',
    '51': 'kveik-north',
    '53': 'kveik-north',
    '54': 'berm',
    '55': 'lithuania',
    '56': 'lithuania',
    '57': 'berm',
    '59': 'russia',
    '6': 'kveik-south',
    '60': 'kveik-south',
    '62': 'kveik-north',
    '63': 'kveik-north',
    '64': 'gong',
    '65': 'kveik-south',
    '66': 'kveik-south',
    '67': 'kveik-south',
    '68': 'lithuania',
    '69': 'kveik-north',
    '7': 'kveik-south',
    '70': 'kveik-north',
    '71': 'kveik-south',
    '72': 'kveik-south',
    '73': 'kveik-south',
    '8': 'kveik-north',
    '9': 'kveik-north',
    'AA': 'kveik-north',
    'AB': 'kveik-north',
    'AC': 'kveik-south',
    'AE': 'kveik-north'
}
